version: '3.4'

services:

  db:
    image: dbgastrocafe
    build: 
     context: ./sqlserver
     dockerfile: Dockerfile
    volumes:
        - ./dockerDB/:/var/opt/mssql/data
    networks:
        - default
    deploy:
        replicas: 1
      
  sanrafael:
    image: ${DOCKER_REGISTRY-}sanrafael
    build:
      context: .
      dockerfile: SanRafael/Dockerfile
    environment:
        - DIRECTORIO=/ocean
    expose:
        - "80"
    depends_on:
        - db
    networks:
        - default
    deploy:
        replicas: 1
      
  nginx-proxy:
    image: nginxgastrocafe
    build: 
     context: ./nginx
     dockerfile: Dockerfile
    expose:
      - 80
    links:
        - sanrafael:sanrafael
    networks:
      - default
      - traefik_public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.ocean.rule=(Host(`feiapps.uv.mx`) && PathPrefix(`/ocean`))"
        - "traefik.http.routers.ocean.entrypoints=web"
        - "traefik.http.routers.ocean.middlewares=https_redirect"
        - "traefik.http.services.ocean.loadbalancer.server.port=80"
        - "traefik.http.services.ocean.loadbalancer.passhostheader=true"
        - "traefik.http.routers.oceansecured.rule=(Host(`feiapps.uv.mx`) && PathPrefix(`/ocean`))"
        - "traefik.http.routers.oceansecured.entrypoints=websecure"
        - "traefik.http.routers.oceansecured.tls.certresolver=myresolver"


networks:
  traefik_public:
      external: true