version: '3.4'

services:

  db:
    image: dbgastrocafe
    build: 
     context: ./sqlserver
     dockerfile: Dockerfile
    volumes:
        - ./dockerDB/:/var/opt/mssql/data
    networks:
        - default
    deploy:
        replicas: 1
      
  sanrafael:
    image: ${DOCKER_REGISTRY-}sanrafael
    build:
      context: .
      dockerfile: SanRafael/Dockerfile
    environment:
        - DIRECTORIO=/ocean
    expose:
        - "80"
    depends_on:
        - db
    networks:
        - default
    deploy:
        replicas: 1
      
  nginx-proxy:
    image: nginxgastrocafe
    build: 
     context: ./nginx
     dockerfile: Dockerfile
    expose:
      - 80
    links:
        - sanrafael:sanrafael


