// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using NUnit.Framework;

namespace GastroCafe_NUnit
{

    [TestFixture]
    public class ModuloRecetasTest
    {
        private const string nombre_dominio = "localhost:63408";
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new FirefoxDriver(Environment.CurrentDirectory);
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }

        public void IniciarSesion()
        {
            driver.Navigate().GoToUrl("http://" + nombre_dominio + "/Account/Login");
            driver.FindElement(By.Id("Email")).SendKeys("gastrocafe@gmail.com");
            driver.FindElement(By.Id("Password")).SendKeys("gastroCafe_123");
            driver.FindElement(By.CssSelector(".btn")).Click();
        }

        //Este caso de prueba necesita del insumo Huevo con presentación y disponible en el inventario. Además, una Área de producción
        [Test]
        public void CP_RegistrarReceta()
        {
            IniciarSesion();
            driver.Navigate().GoToUrl("http://" + nombre_dominio + "/Recetas/Create");
            driver.FindElement(By.Id("Nombre")).Click();
            driver.FindElement(By.Id("Nombre")).SendKeys("Huevos con jamón");
            driver.FindElement(By.Id("MetodoPreparacion")).SendKeys("Batir dos huevos con una rebanada de jamón en un bol, " +
                "verter en un sartén con aceite caliente");
            driver.FindElement(By.Id("Porciones")).SendKeys("10");
            driver.FindElement(By.CssSelector(".form-group:nth-child(4) .btn")).Click();
            driver.FindElement(By.Id("TipoReceta")).SendKeys("Preparación");
            driver.FindElement(By.Id("Clasificacion")).SendKeys("Desayuno");
            driver.FindElement(By.Id("AreaProduccion")).Click();
            driver.FindElement(By.Id("ingredientes-tab")).Click();
            driver.FindElement(By.LinkText("+")).Click();
            driver.FindElement(By.Id("txtBuscarInsumoModal")).SendKeys("Hue");
            driver.FindElement(By.LinkText("Agregar")).Click();
            driver.FindElement(By.Id("cantidadInsumoConfig")).Clear();
            driver.FindElement(By.Id("cantidadInsumoConfig")).SendKeys("2");
            driver.FindElement(By.Id("addInsumoConfigurado")).Click();
            driver.FindElement(By.Id("costos-tab")).Click();
            driver.FindElement(By.Id("PrecioDefinidoPorUsuario")).SendKeys("40");
            driver.FindElement(By.CssSelector("#costos > .form-group:nth-child(5)")).Click();
            driver.FindElement(By.Id("submitReceta")).Click();
            driver.FindElement(By.Name("searchQuery")).Clear();
            driver.FindElement(By.Name("searchQuery")).SendKeys("Huevos con jamón");
            driver.FindElement(By.CssSelector(".form-group > .btn")).Click();
            Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(1)")).Text, Is.EqualTo("Huevos con jamón"));
        }
        [Test]
        public void CP_ModificarReceta()
        {
            IniciarSesion();
            driver.Navigate().GoToUrl("http://" + nombre_dominio + "/Recetas");
            driver.FindElement(By.LinkText("Editar")).Click();
            driver.FindElement(By.Id("Nombre")).Clear();
            driver.FindElement(By.Id("Nombre")).SendKeys("Huevos fritos");
            driver.FindElement(By.Id("Porciones")).Clear();
            driver.FindElement(By.Id("Porciones")).SendKeys("12");
            driver.FindElement(By.Id("Clasificacion")).Clear();
            driver.FindElement(By.Id("Clasificacion")).SendKeys("Desayuno");
            driver.FindElement(By.Id("PrecioDefinidoPorUsuario")).Clear();
            driver.FindElement(By.Id("PrecioDefinidoPorUsuario")).SendKeys("25");
            driver.FindElement(By.Id("submitEditReceta")).Click();
            driver.FindElement(By.Name("searchQuery")).SendKeys("Huevos fritos");
            driver.FindElement(By.CssSelector(".form-group > .btn")).Click();
            driver.FindElement(By.CssSelector("tr:nth-child(1) .btn-info")).Click();
            Assert.That(driver.FindElement(By.CssSelector(".col-sm-9:nth-child(6)")).Text, Is.EqualTo("12.00"));
            Assert.That(driver.FindElement(By.CssSelector(".col-sm-9:nth-child(10)")).Text, Is.EqualTo("Desayuno"));
            Assert.That(driver.FindElement(By.CssSelector(".col-sm-9:nth-child(24)")).Text, Is.EqualTo("$25.00"));
        }

        //Para este caso de prueba solo debe existir una receta, DEJAR PARA LO ÚLTIMO ESTE CASO, ya que no se pueden habilitar las recetas
        [Test]
        public void CP_DeshabilitarReceta()
        {
            IniciarSesion();
            driver.FindElement(By.LinkText("Recetas")).Click();
            driver.FindElement(By.LinkText("Dar de baja")).Click();
            driver.FindElement(By.CssSelector(".btn-default")).Click();
            {
                var elements = driver.FindElements(By.CssSelector("td:nth-child(1)"));
                Assert.True(elements.Count == 0);
            }
        }
        [Test]
        public void CP_CrearRecetaConCamposVacios()
        {
            IniciarSesion();
            driver.Navigate().GoToUrl("http://" + nombre_dominio + "/Recetas/Create");
            driver.FindElement(By.Id("ingredientes-tab")).Click();
            var elements = driver.FindElements(By.Id("Nombre-error"));
            Assert.True(elements.Count > 0);
        }
        [Test]
        public void CP_CrearRecetaConNumeroDePorcionesNegativa()
        {
            IniciarSesion();
            driver.Navigate().GoToUrl("http://" + nombre_dominio + "/Recetas/Create");
            driver.FindElement(By.Id("Nombre")).Click();
            driver.FindElement(By.Id("Nombre")).SendKeys("Huevos con jamón 2");
            driver.FindElement(By.Id("MetodoPreparacion")).SendKeys("Batir dos huevos con una rebanada de jamón en un bol, " +
                "verter en un sartén con aceite caliente");
            driver.FindElement(By.Id("Porciones")).SendKeys("-10");
            driver.FindElement(By.CssSelector(".form-group:nth-child(4) .btn")).Click();
            driver.FindElement(By.Id("TipoReceta")).SendKeys("Preparación");
            driver.FindElement(By.Id("Clasificacion")).SendKeys("Desayuno");
            driver.FindElement(By.Id("AreaProduccion")).Click();
            driver.FindElement(By.Id("ingredientes-tab")).Click();
            var elements = driver.FindElements(By.Id("Porciones-error"));
            Assert.True(elements.Count > 0);
        }
        [Test]
        public void CP_EditarRecetaConNumeroDePorcionesNegativa()
        {
            IniciarSesion();
            driver.Navigate().GoToUrl("http://" + nombre_dominio + "/Recetas");
            driver.FindElement(By.LinkText("Editar")).Click();
            driver.FindElement(By.Id("Porciones")).Clear();
            driver.FindElement(By.Id("Porciones")).SendKeys("-1");
            driver.FindElement(By.Id("submitEditReceta")).Click();
            var elements = driver.FindElements(By.Id("Porciones-error"));
            Assert.True(elements.Count > 0);
        }

        //Para este caso de prueba debe existir una receta con el nombre ingresado en el script de la prueba
        [Test]
        public void CP_RegistrarRecetaRepetida()
        {
            IniciarSesion();
            driver.Navigate().GoToUrl("http://" + nombre_dominio + "/Recetas/Create");
            driver.FindElement(By.Id("Nombre")).Click();
            driver.FindElement(By.Id("Nombre")).SendKeys("Huevos con jamón");
            driver.FindElement(By.Id("MetodoPreparacion")).SendKeys("Batir dos huevos con una rebanada de jamón en un bol, " +
                "verter en un sartén con aceite caliente");
            driver.FindElement(By.Id("Porciones")).SendKeys("10");
            driver.FindElement(By.CssSelector(".form-group:nth-child(4) .btn")).Click();
            driver.FindElement(By.Id("TipoReceta")).SendKeys("Preparación");
            driver.FindElement(By.Id("Clasificacion")).SendKeys("Desayuno");
            driver.FindElement(By.Id("AreaProduccion")).Click();
            var elements = driver.FindElements(By.Id("Nombre-error"));
            Assert.True(elements.Count > 0);
        }
    }
}
