// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using NUnit.Framework;

namespace GastroCafe_NUnit
{

    [TestFixture]
    public class ModuloInsumoRealTest
    {
        private const string nombre_dominio = "localhost:63408";
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new FirefoxDriver(Environment.CurrentDirectory);
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }

        public void IniciarSesion()
        {
            driver.Navigate().GoToUrl("http://" + nombre_dominio + "/Account/Login");
            driver.FindElement(By.Id("Email")).SendKeys("gastrocafe@gmail.com");
            driver.FindElement(By.Id("Password")).SendKeys("gastroCafe_123");
            driver.FindElement(By.CssSelector(".btn")).Click();
        }
        [Test]
        public void CP_RegistrarInsumoCamposVacios()
        {
            IniciarSesion();
            driver.FindElement(By.Id("navbarDropdown")).Click();
            driver.FindElement(By.LinkText("Administración de insumos")).Click();
            driver.FindElement(By.LinkText("Registrar nuevo Insumo")).Click();
            driver.FindElement(By.Id("btn_submit_insumo")).Click();
            var elementsNombre = driver.FindElements(By.Id("Nombre-error"));
            Assert.True(elementsNombre.Count > 0);
            var elementsTienda = driver.FindElements(By.Id("Tienda-error"));
            Assert.True(elementsTienda.Count > 0);
            var elements = driver.FindElements(By.Id("UnidadId-error"));
            Assert.True(elements.Count > 0);
            var elementsPrecio = driver.FindElements(By.Id("Precio-error"));
            Assert.True(elementsPrecio.Count > 0);
            var elementsStockMinimo = driver.FindElements(By.Id("StockMinimo-error"));
            Assert.True(elementsStockMinimo.Count > 0);
        }
        [Test]
        public void CP_RegistrarInsumoSinCategoria()
        {
            IniciarSesion();
            driver.FindElement(By.Id("navbarDropdown")).Click();
            driver.FindElement(By.LinkText("Administración de insumos")).Click();
            driver.FindElement(By.LinkText("Registrar nuevo Insumo")).Click();
            driver.FindElement(By.Id("Nombre")).SendKeys("Aguacate");
            driver.FindElement(By.Id("Tienda")).SendKeys("Fasti");
            driver.FindElement(By.Id("UnidadId")).Click();
            {
                var dropdown = driver.FindElement(By.Id("UnidadId"));
                dropdown.FindElement(By.XPath("//option[. = 'Kilogramo']")).Click();
            }
            driver.FindElement(By.Id("Precio")).SendKeys("38");
            driver.FindElement(By.Id("StockMinimo")).SendKeys("1");
            driver.FindElement(By.Id("btn_submit_insumo")).Click();
            {
                var elements = driver.FindElements(By.CssSelector("span:nth-child(1)"));
                Assert.True(elements.Count > 0);
            }
        }
        [Test]
        public void CP_RegistrarInsumoPrecioNegativo()
        {
            IniciarSesion();
            driver.FindElement(By.Id("navbarDropdown")).Click();
            driver.FindElement(By.LinkText("Administración de insumos")).Click();
            driver.FindElement(By.LinkText("Registrar nuevo Insumo")).Click();
            driver.FindElement(By.Id("Nombre")).SendKeys("Aguacate");
            driver.FindElement(By.Id("Tienda")).SendKeys("Fasti");
            driver.FindElement(By.Id("select_categoria")).Click();
            {
                var dropdown = driver.FindElement(By.Id("select_categoria"));
                dropdown.FindElement(By.XPath("//option[. = 'Verdura']")).Click();
            }
            driver.FindElement(By.Id("UnidadId")).Click();
            {
                var dropdown = driver.FindElement(By.Id("UnidadId"));
                dropdown.FindElement(By.XPath("//option[. = 'Kilogramo']")).Click();
            }
            driver.FindElement(By.Id("Precio")).SendKeys("-38");
            driver.FindElement(By.Id("StockMinimo")).SendKeys("1");
            driver.FindElement(By.Id("btn_submit_insumo")).Click();
            var elements = driver.FindElements(By.Id("Precio-error"));
            Assert.True(elements.Count > 0);
        }
        [Test]
        public void CP_RegistrarInsumoStockMinimoNegativo()
        {
            IniciarSesion();
            driver.FindElement(By.Id("navbarDropdown")).Click();
            driver.FindElement(By.LinkText("Administración de insumos")).Click();
            driver.FindElement(By.LinkText("Registrar nuevo Insumo")).Click();
            driver.FindElement(By.Id("Nombre")).SendKeys("Aguacate");
            driver.FindElement(By.Id("Tienda")).SendKeys("Fasti");
            driver.FindElement(By.Id("select_categoria")).Click();
            {
                var dropdown = driver.FindElement(By.Id("select_categoria"));
                dropdown.FindElement(By.XPath("//option[. = 'Verdura']")).Click();
            }
            driver.FindElement(By.CssSelector("#select_categoria > option:nth-child(3)")).Click();
            driver.FindElement(By.Id("UnidadId")).Click();
            {
                var dropdown = driver.FindElement(By.Id("UnidadId"));
                dropdown.FindElement(By.XPath("//option[. = 'Kilogramo']")).Click();
            }
            driver.FindElement(By.CssSelector("#UnidadId > option:nth-child(2)")).Click();
            driver.FindElement(By.Id("Precio")).Click();
            driver.FindElement(By.Id("Precio")).SendKeys("38");
            driver.FindElement(By.Id("StockMinimo")).Click();
            driver.FindElement(By.Id("StockMinimo")).SendKeys("-1");
            driver.FindElement(By.Id("btn_submit_insumo")).Click();
            var elements = driver.FindElements(By.Id("StockMinimo-error"));
            Assert.True(elements.Count > 0);
        }

        //Este caso de prueba necesita la categoría Verdura
        [Test]
        public void CP_RegistrarInsumos()
        {
            IniciarSesion();
            driver.Navigate().GoToUrl("http://" + nombre_dominio + "/Insumos/Create");
            driver.FindElement(By.Id("Nombre")).SendKeys("Aguacate");
            driver.FindElement(By.Id("Tienda")).SendKeys("Fasti");
            driver.FindElement(By.Id("select_categoria")).Click();
            {
                var dropdown = driver.FindElement(By.Id("select_categoria"));
                dropdown.FindElement(By.XPath("//option[. = 'Verdura']")).Click();
            }
            driver.FindElement(By.Id("UnidadId")).Click();
            {
                var dropdown = driver.FindElement(By.Id("UnidadId"));
                dropdown.FindElement(By.XPath("//option[. = 'Kilogramo']")).Click();
            }
            driver.FindElement(By.Id("Precio")).SendKeys("38");
            driver.FindElement(By.Id("StockMinimo")).SendKeys("2.5");
            driver.FindElement(By.Id("btn_submit_insumo")).Click();
            driver.FindElement(By.Id("txtBuscar")).SendKeys("Aguacate");
            driver.FindElement(By.Id("btnBuscar")).Click();
            Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(1)")).Text, Is.EqualTo("Aguacate"));
        }
        [Test]
        public void CP_EditarInsumoStockMinimoNegativo()
        {
            IniciarSesion();
            driver.FindElement(By.Id("navbarDropdown")).Click();
            driver.FindElement(By.LinkText("Administración de insumos")).Click();
            driver.FindElement(By.Id("txtBuscar")).SendKeys("Aguacate");
            driver.FindElement(By.Id("btnBuscar")).Click();
            driver.FindElement(By.LinkText("Editar")).Click();
            driver.FindElement(By.Id("StockMinimo")).Clear();
            driver.FindElement(By.Id("StockMinimo")).SendKeys("-1");
            driver.FindElement(By.Id("btn_submit_insumo")).Click();
            var elements = driver.FindElements(By.Id("StockMinimo-error"));
            Assert.True(elements.Count > 0);
        }
        [Test]
        public void CP_EditarInsumoPrecioNegativo()
        {
            IniciarSesion();
            driver.FindElement(By.Id("navbarDropdown")).Click();
            driver.FindElement(By.LinkText("Administración de insumos")).Click();
            driver.FindElement(By.Id("txtBuscar")).SendKeys("Aguacate");
            driver.FindElement(By.Id("btnBuscar")).Click();
            driver.FindElement(By.LinkText("Editar")).Click();
            driver.FindElement(By.Id("Precio")).Clear();
            driver.FindElement(By.Id("Precio")).SendKeys("-38");
            driver.FindElement(By.Id("btn_submit_insumo")).Click();
            var elements = driver.FindElements(By.Id("Precio-error"));
            Assert.True(elements.Count > 0);
        }
        [Test]
        public void CP_ConsultarInsumos()
        {
            IniciarSesion();
            driver.FindElement(By.Id("navbarDropdown")).Click();
            driver.FindElement(By.LinkText("Administración de insumos")).Click();
            Assert.That(driver.Title, Is.EqualTo("Insumos - Gastrocafé"));
            driver.FindElement(By.Id("txtBuscar")).SendKeys("Aguacate");
            driver.FindElement(By.Id("btnBuscar")).Click();
            Assert.That(driver.FindElement(By.CssSelector("td:nth-child(1)")).Text, Is.EqualTo("Aguacate"));
            var elements = driver.FindElements(By.CssSelector("tr:nth-child(1) > td:nth-child(1)"));
            Assert.True(elements.Count > 0);
        }
        [Test]
        public void CP_EditarInsumos()
        {
            IniciarSesion();
            driver.Navigate().GoToUrl("http://" + nombre_dominio + "/Insumos");
            driver.FindElement(By.Id("txtBuscar")).SendKeys("Aguacate");
            driver.FindElement(By.Id("btnBuscar")).Click();
            driver.FindElement(By.LinkText("Editar")).Click();
            driver.FindElement(By.Id("Nombre")).Clear();
            driver.FindElement(By.Id("Nombre")).SendKeys("Aguacate");
            driver.FindElement(By.Id("Tienda")).Clear();
            driver.FindElement(By.Id("Tienda")).SendKeys("Fasti");
            driver.FindElement(By.Id("Precio")).Clear();
            driver.FindElement(By.Id("Precio")).SendKeys("38");
            driver.FindElement(By.Id("StockMinimo")).Clear();
            driver.FindElement(By.Id("StockMinimo")).SendKeys("1");
            driver.FindElement(By.Id("btn_submit_insumo")).Click();
            driver.FindElement(By.Id("txtBuscar")).SendKeys("Aguacate");
            driver.FindElement(By.Id("btnBuscar")).Click();
            driver.FindElement(By.CssSelector("tr:nth-child(1) .btn-info")).Click();
            Assert.That(driver.FindElement(By.CssSelector(".col-sm-9:nth-child(4)")).Text, Is.EqualTo("Fasti"));
            Assert.That(driver.FindElement(By.CssSelector(".col-sm-9:nth-child(12)")).Text, Is.EqualTo("38"));
            Assert.That(driver.FindElement(By.CssSelector(".col-sm-9:nth-child(14)")).Text, Is.EqualTo("1.00"));
        }
        [Test]
        public void CP_DeshabilitarInsumo()
        {
            IniciarSesion();
            driver.FindElement(By.Id("navbarDropdown")).Click();
            driver.FindElement(By.LinkText("Administración de insumos")).Click();
            driver.FindElement(By.Id("txtBuscar")).SendKeys("Aguacate");
            driver.FindElement(By.Id("btnBuscar")).Click();
            driver.FindElement(By.LinkText("Deshabilitar")).Click();
            driver.FindElement(By.CssSelector(".btn-danger")).Click();
            driver.FindElement(By.LinkText("Regresar al Listado")).Click();
            driver.FindElement(By.Id("txtBuscar")).SendKeys("Aguacate");
            driver.FindElement(By.Id("btnBuscar")).Click();
            {
                var elementsChild = driver.FindElements(By.CssSelector("td:nth-child(1)"));
                Assert.True(elementsChild.Count == 0);
            }
        }
        [Test]
        public void CP_HabilitarInsumo()
        {
            IniciarSesion();
            driver.FindElement(By.Id("navbarDropdown")).Click();
            driver.FindElement(By.LinkText("Administración de insumos")).Click();
            driver.FindElement(By.Id("txtBuscar")).SendKeys("Aguacate");
            driver.FindElement(By.Id("btnBuscar")).Click();
            driver.FindElement(By.CssSelector(".form-group:nth-child(2) > .btn")).Click();
            driver.FindElement(By.LinkText("Deshabilitado")).Click();
            driver.FindElement(By.LinkText("Habilitar")).Click();
            driver.FindElement(By.CssSelector(".btn-secondary")).Click();
            driver.FindElement(By.LinkText("Regresar al Listado")).Click();
            driver.FindElement(By.Id("txtBuscar")).SendKeys("Aguacate");
            driver.FindElement(By.Id("btnBuscar")).Click();
            {
                var elementsChild = driver.FindElements(By.CssSelector("td:nth-child(1)"));
                Assert.True(elementsChild.Count > 0);
            }
        }
    }
}