// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using NUnit.Framework;

namespace GastroCafe_NUnit
{

    [TestFixture]
    public class ModuloPresentacionTest
    {
        private const string nombre_dominio = "localhost:63408";
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new FirefoxDriver(Environment.CurrentDirectory);
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }

        public void IniciarSesion()
        {
            driver.Navigate().GoToUrl("http://" + nombre_dominio + "/Account/Login");
            driver.FindElement(By.Id("Email")).SendKeys("gastrocafe@gmail.com");
            driver.FindElement(By.Id("Password")).SendKeys("gastroCafe_123");
            driver.FindElement(By.CssSelector(".btn")).Click();
        }

        [Test]
        public void CP_AgregarPresentacionCamposVacios()
        {
            IniciarSesion();
            driver.FindElement(By.Id("navbarDropdown")).Click();
            driver.FindElement(By.LinkText("Presentaciones de insumos")).Click();
            driver.FindElement(By.CssSelector(".img")).Click();
            driver.FindElement(By.Id("btnAgregarPre")).Click();
            driver.FindElement(By.CssSelector(".btn-block")).Click();
            var elements = driver.FindElements(By.Id("nombre-error"));
            Assert.True(elements.Count > 0);
            var elements_presentacion = driver.FindElements(By.Id("presentacionPrecio-error"));
            Assert.True(elements_presentacion.Count > 0);
            var elements_unidades = driver.FindElements(By.Id("unidades-error"));
            Assert.True(elements_unidades.Count > 0);
            var elements_preciounitario = driver.FindElements(By.Id("precioUnitario-error"));
            Assert.True(elements_preciounitario.Count > 0);
        }
        [Test]
        public void CP_AgregarPresentacionPrecioNegativo()
        {
            IniciarSesion();
            driver.FindElement(By.Id("navbarDropdown")).Click();
            driver.FindElement(By.LinkText("Presentaciones de insumos")).Click();
            driver.FindElement(By.CssSelector(".img")).Click();
            driver.FindElement(By.Id("btnAgregarPre")).Click();
            driver.FindElement(By.Id("nombre")).SendKeys("costal");
            driver.FindElement(By.Id("presentacionPrecio")).SendKeys("-60");
            driver.FindElement(By.Id("unidades")).SendKeys("10");
            driver.FindElement(By.Id("precioUnitario")).Clear();
            driver.FindElement(By.Id("precioUnitario")).SendKeys("-6.00");
            var elements = driver.FindElements(By.Id("presentacionPrecio-error"));
            Assert.True(elements.Count > 0);
            driver.FindElement(By.CssSelector(".btn-block")).Click();
        }
        [Test]
        public void CP_AgregarPresentacionCantidadNegativa()
        {
            IniciarSesion();
            driver.FindElement(By.Id("navbarDropdown")).Click();
            driver.FindElement(By.LinkText("Presentaciones de insumos")).Click();
            driver.FindElement(By.CssSelector(".img")).Click();
            driver.FindElement(By.Id("btnAgregarPre")).Click();
            driver.FindElement(By.Id("nombre")).SendKeys("costal");
            driver.FindElement(By.Id("presentacionPrecio")).SendKeys("60");
            driver.FindElement(By.Id("unidades")).SendKeys("-10");
            driver.FindElement(By.Id("precioUnitario")).Click();
            var elements = driver.FindElements(By.Id("unidades-error"));
            Assert.True(elements.Count > 0);
            driver.FindElement(By.Id("precioUnitario")).Clear();
            driver.FindElement(By.Id("precioUnitario")).SendKeys("-6.00");
            driver.FindElement(By.CssSelector(".btn-block")).Click();
        }

        //Para este caso de prueba, checar que el insumo no tenga ninguna presentación registrada anteriormente
        [Test]
        public void CP_AgregarPresentacion()
        {
            IniciarSesion();
            driver.FindElement(By.Id("navbarDropdown")).Click();
            driver.FindElement(By.LinkText("Presentaciones de insumos")).Click();
            driver.FindElement(By.CssSelector(".nombrePresentacion")).Click();
            driver.FindElement(By.Id("btnAgregarPre")).Click();
            driver.FindElement(By.Id("nombre")).SendKeys("caja");
            driver.FindElement(By.Id("presentacionPrecio")).SendKeys("50");
            driver.FindElement(By.Id("unidades")).SendKeys("10.5");
            driver.FindElement(By.Id("precioUnitario")).Clear();
            driver.FindElement(By.Id("precioUnitario")).SendKeys("2.50");
            driver.FindElement(By.CssSelector(".btn-block")).Click();
            driver.FindElement(By.CssSelector(".nombrePresentacion")).Click();
            Assert.That(driver.FindElement(By.CssSelector("td:nth-child(1)")).Text, Is.EqualTo("caja"));
        }
        [Test]
        public void CP_EditarPresentacionCantidadNegativa()
        {
            IniciarSesion();
            driver.FindElement(By.Id("navbarDropdown")).Click();
            driver.FindElement(By.LinkText("Presentaciones de insumos")).Click();
            driver.FindElement(By.CssSelector(".nombrePresentacion")).Click();
            driver.FindElement(By.LinkText("Editar")).Click();
            driver.FindElement(By.Id("unidades")).Clear();
            driver.FindElement(By.Id("unidades")).SendKeys("-10");
            driver.FindElement(By.Id("precioUnitario")).Clear();
            driver.FindElement(By.Id("precioUnitario")).SendKeys("-6.00");
            driver.FindElement(By.CssSelector(".btn-block")).Click();
        }
        [Test]
        public void CP_EditarPresentacionPrecioNegativo()
        {
            IniciarSesion();
            driver.FindElement(By.Id("navbarDropdown")).Click();
            driver.FindElement(By.LinkText("Presentaciones de insumos")).Click();
            driver.FindElement(By.CssSelector(".nombrePresentacion")).Click();
            driver.FindElement(By.LinkText("Editar")).Click();
            driver.FindElement(By.Id("presentacionPrecio")).Clear();
            driver.FindElement(By.Id("presentacionPrecio")).SendKeys("-60");
            driver.FindElement(By.Id("precioUnitario")).Clear();
            driver.FindElement(By.Id("precioUnitario")).SendKeys("-6.00");
            var elements = driver.FindElements(By.Id("presentacionPrecio-error"));
            Assert.True(elements.Count > 0);
            driver.FindElement(By.CssSelector(".btn-block")).Click();
        }
        [Test]
        public void CP_EditarPresentacion()
        {
            IniciarSesion();
            driver.FindElement(By.Id("navbarDropdown")).Click();
            driver.FindElement(By.LinkText("Presentaciones de insumos")).Click();
            driver.FindElement(By.CssSelector(".nombrePresentacion")).Click();
            driver.FindElement(By.LinkText("Editar")).Click();
            driver.FindElement(By.Id("nombre")).Clear();
            driver.FindElement(By.Id("nombre")).SendKeys("costal");
            driver.FindElement(By.Id("presentacionPrecio")).Clear();
            driver.FindElement(By.Id("presentacionPrecio")).SendKeys("60");
            driver.FindElement(By.Id("unidades")).Clear();
            driver.FindElement(By.Id("unidades")).SendKeys("10");
            driver.FindElement(By.Id("precioUnitario")).Clear();
            driver.FindElement(By.Id("precioUnitario")).SendKeys("6.00");
            driver.FindElement(By.CssSelector(".btn-block")).Click();
            driver.FindElement(By.CssSelector(".imgText")).Click();
            Assert.That(driver.FindElement(By.CssSelector("td:nth-child(1)")).Text, Is.EqualTo("costal"));
        }
        [Test]
        public void CP_ConsultarPresentaciones()
        {
            IniciarSesion();
            driver.Navigate().GoToUrl("http://" + nombre_dominio + "/Presentaciones/VerInsumos");
            var elements = driver.FindElements(By.CssSelector(".nombrePresentacion"));
            Assert.True(elements.Count > 0);
        }
        [Test]
        public void CP_DetallesPresentacion()
        {
            IniciarSesion();
            driver.FindElement(By.Id("navbarDropdown")).Click();
            driver.FindElement(By.LinkText("Presentaciones de insumos")).Click();
            driver.FindElement(By.CssSelector(".nombrePresentacion")).Click();
            driver.FindElement(By.LinkText("Detalles")).Click();
            Assert.That(driver.FindElement(By.CssSelector("dd:nth-child(2)")).Text, Is.EqualTo("costal"));
            Assert.That(driver.FindElement(By.CssSelector("dd:nth-child(4)")).Text, Is.EqualTo("10"));
            Assert.That(driver.FindElement(By.CssSelector("dd:nth-child(6)")).Text, Is.EqualTo("60"));
            Assert.That(driver.FindElement(By.CssSelector("dd:nth-child(8)")).Text, Is.EqualTo("6"));
        }
        [Test]
        public void CP_EliminarPresentacion()
        {
            IniciarSesion();
            driver.FindElement(By.Id("navbarDropdown")).Click();
            driver.FindElement(By.LinkText("Presentaciones de insumos")).Click();
            driver.FindElement(By.CssSelector(".nombrePresentacion")).Click();
            driver.FindElement(By.LinkText("Eliminar")).Click();
            driver.FindElement(By.CssSelector(".btn-primary")).Click();
            var elements = driver.FindElements(By.CssSelector("td:nth-child(1)"));
            Assert.True(elements.Count == 0);
        }

        [Test]
        public void CP_RegistrarPresentacionRepetida()
        {
            IniciarSesion();
            driver.FindElement(By.Id("navbarDropdown")).Click();
            driver.FindElement(By.LinkText("Presentaciones de insumos")).Click();
            driver.FindElement(By.CssSelector(".nombrePresentacion")).Click();
            driver.FindElement(By.Id("btnAgregarPre")).Click();
            driver.FindElement(By.Id("nombre")).SendKeys("caja");
            driver.FindElement(By.Id("presentacionPrecio")).SendKeys("40");
            driver.FindElement(By.Id("unidades")).SendKeys("16");
            driver.FindElement(By.CssSelector(".btn-block")).Click();
            var elements = driver.FindElements(By.Id("nombre-error"));
            Assert.True(elements.Count > 0);
        }
    }
}