FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf
# COPY default.crt /etc/nginx/certs/default.crt
# COPY default.key /etc/nginx/certs/default.key
# COPY dhparam.pem /etc/nginx/dhparam/dhparam.pem
# COPY default.conf /etc/nginx/conf.d/default.conf
# COPY wwwroot/ /var/www/app/wwwroot